### PR TITLE
fix: support NO_COLOR for ts diagnostics

### LINKED ISSUE #213: NO_COLOR
I get less color with `NO_COLOR=true deno run build_script.ts` compared to `deno run build_script.ts` but it looks like some subprocesses still print with color:

```console
% NO_COLOR=true deno run build_script.ts
[dnt] Transforming...
[dnt] Running npm install...

added 11 packages, and audited 12 packages in 711ms

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[dnt] Building project...
[dnt] Type checking...
[96msrc/Deque/add.ts[0m:[93m8[0m:[93m16[0m - [91merror[0m[90m TS2691: [0mAn import path cannot end with a '.ts' extension. Consider importing '../Deque.js' instead.

…

```

I've tried `export NO_COLOR=true` in `~/.zshrc` and re-sourcing too but to no avail.

### PR DESCRIPTION
**Pull request by dsherret**
Closes #213

### CODE REVIEW

File: lib/compiler.ts [hunk 1]
```diff
@@ -4,11 +4,15 @@ import { path, ts } from "./mod.deps.ts";
...
-  console.error(ts.formatDiagnosticsWithColorAndContext(diagnostics, {
+  const host: ts.FormatDiagnosticsHost = {
     getCanonicalFileName: (fileName) => path.resolve(fileName),
     getCurrentDirectory: () => Deno.cwd(),
     getNewLine: () => "\n",
-  }));
+  };
+  const output = Deno.env.get("NO_COLOR") == null
+    ? ts.formatDiagnosticsWithColorAndContext(diagnostics, host)
+    : ts.formatDiagnostics(diagnostics, host);
```
Comment (mfulton26) [inline lib/compiler.ts:14]: `Deno.noColor` can be used so that `dnt` doesn't require additional permissions to access the environment variable

```suggestion
  const output = Deno.noColor
    ? ts.formatDiagnostics(diagnostics, host)
    : ts.formatDiagnosticsWithColorAndContext(diagnostics, host);
```

Comment (dsherret) [reply lib/compiler.ts:14]: Oh, I didn't know about this property. I opened https://github.com/denoland/dnt/pull/223
